version: "3"
services:
  main:
    container_name: main
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5000:5000
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always


  postgres:
    container_name: postgres
    image: postgres:14
    environment:
      POSTGRES_DB: blocknote
      POSTGRES_USER: blocknote
      POSTGRES_PASSWORD: blocknote
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
